title: "Joel Thibaud Donfack Nguekouo"
logo: img/Photo_Thibaud.jpj
description: "Portfolio Ingenieur en mecatronique, conception mecaniques et developpement produit"
show_downloads: true
theme:jekyl-theme-minimal 
lang: fr 
