#title: "Joel Thibaud Donfack Nguekouo"
logo: img/Photo_Thibaud.jpg
description: "Portfolio Ingenieur en mecatronique, conception mecaniques et developpement produit"
show_downloads: true
theme: jekyll-theme-minimal 
lang: fr 
